name: "🐛 Баг-репорт"
description: "Сообщить об ошибке."
body:
  - type: markdown
    attributes:
      value: "Что произошло? Где? Когда?."

  - type: textarea
    id: description
    attributes:
      label: "Описание проблемы своими словами"
      description: "Что именно происходит и в каком месте."
      placeholder: "Опишите проблему так, как видите вы..."
    validations:
      required: true

  - type: checkboxes
    id: environment
    attributes:
      label: "Окружение"
      description: "Браузер(ы), в котором воспроизводится. Можно отметить несколько."
      options:
        - label: "Chrome"
        - label: "Safari"
        - label: "Firefox"
        - label: "Яндекс.Браузер"

  - type: input
    id: browser_version
    attributes:
      label: "Версия браузера"
      placeholder: "Например: 133.0.6943.127 (64 бит)"

  - type: textarea
    id: preconditions
    attributes:
      label: "Предварительные условия"
      description: "Что нужно сделать до воспроизведения (например, войти в личный кабинет)."
      placeholder: "Действия, которые нужно выполнить перед тестированием (например, войти в личный кабинет)"

  - type: textarea
    id: steps
    attributes:
      label: "Шаги воспроизведения *"
      description: "Последовательность действий, ведущих к ошибке."
      placeholder: "Куда нажимать, чтобы воспроизвести ошибку? Последовательность шагов."
      value: |
        1. Перейти на страницу X
        2. Нажать здесь
        3. Нажать там
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Фактический результат *"
      placeholder: "Что имеем по факту?"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Ожидаемый результат *"
      placeholder: "Что хотели получить? (руководствуемся документацией и логикой)"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Серьёзность"
      description: "Заполняется QA. Влияние дефекта на работоспособность."
      options:
        - "Blocker"
        - "Critical"
        - "Major"
        - "Minor"
        - "Trivial"

